[project]
name = "fastapi-sqlalchemy-asyncpg"
version = "0.18.0"
description = "A modern FastAPI application with SQLAlchemy 2.0 and AsyncPG for high-performance async database operations. Features include JWT authentication with Redis token storage, password hashing, connection pooling, data processing with Polars, Rich logging, task scheduling with APScheduler, and Shakespeare datasets integration."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[all]>=0.115.12",
    "pydantic[email]>=2.11.4",
    "pydantic-settings>=2.9.1",
    "sqlalchemy>=2.0.40",
    "uvicorn[standard]>=0.34.2",
    "asyncpg>=0.30.0",
    "alembic>=1.15.2",
    "httpx>=0.28.1",
    "pytest>=8.3.5",
    "pytest-cov>=6.1.1",
    "uvloop>=0.21.0",
    "httptools>=0.6.4",
    "rich>=14.0.0",
    "pyjwt>=2.10.1",
    "redis>=6.0.0",
    "bcrypt>=4.3.0",
    "polars>=1.29.0",
    "python-multipart>=0.0.20",
    "fastexcel>=0.14.0",
    "inline-snapshot>=0.23.0",
    "dirty-equals>=0.9.0",
    "polyfactory>=2.21.0",
    "granian>=2.2.5",
    "apscheduler[redis,sqlalchemy]>=4.0.0a6",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.9.10",
    "devtools[pygments]>=0.12.2",
    "pyupgrade>=3.19.1",
    "ipython>=9.0.2",
    "sqlacodegen>=3.0.0",
    "tryceratops>=2.4.1",
    "locust>=2.33.0"

]


[tool.mypy]
strict = true
exclude = ["venv", ".venv", "alembic"]

[tool.ruff]
target-version = "py313"
exclude = ["alembic"]

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "ARG001", # unused arguments in functions
]
ignore = [
    "E501",  # line too long, handled by black
    "B008",  # do not perform function calls in argument defaults
    "W191",  # indentation contains tabs
    "B904",  # Allow raising exceptions without from e, for HTTPException
]

[tool.ruff.lint.pyupgrade]
# Preserve types, even if a file imports `from __future__ import annotations`.
keep-runtime-typing = true