[project]
name = "fastapi-sqlalchemy-asyncpg"
version = "0.1.0"
description = "A modern FastAPI application with SQLAlchemy 2.0 and AsyncPG for high-performance async database operations. Features include JWT authentication with Redis token storage, password hashing, connection pooling, data processing with Polars, Rich logging, task scheduling with APScheduler, and Shakespeare datasets integration."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[all]>=0.115.6",
    "pydantic[email]>=2.10.3",
    "pydantic-settings>=2.7.0",
    "sqlalchemy>=2.0.36",
    "uvicorn[standard]>=0.34.0",
    "asyncpg>=0.30.0",
    "alembic>=1.14.0",
    "httpx>=0.28.1",
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
    "uvloop>=0.21.0",
    "httptools>=0.6.4",
    "rich>=13.9.4",
    "pyjwt[cryptography]>=2.10.1",
    "redis>=5.2.1",
    "bcrypt>=4.2.1",
    "polars>=1.17.1",
    "python-multipart>=0.0.20",
    "fastexcel>=0.12.0",
    "fastapi-cache2>=0.2.1",
    "inline-snapshot>=0.17.0",
    "dirty-equals>=0.8.0",
    "polyfactory>=2.18.1",
    "granian>=1.7.0",
    "apscheduler[redis,sqlalchemy]>=4.0.0a5",
    "pendulum @ git+https://github.com/sdispater/pendulum.git@develop"
]