[tool.poetry]
name = "fastapi-sqlalchemy-asyncpg"
version = "0.0.15"
description = ""
authors = ["Jakub Miazek <the@grillazz.com>"]
packages = []
license = "MIT"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = {version = "^0.112.2", extras = ["all"]}
pydantic = {version = "^2.8.2", extras = ["email"]}
pydantic-settings = "^2.4.0"
sqlalchemy = "^2.0.32"
uvicorn = { version = "^0.30.6", extras = ["standard"]}
asyncpg = "^0.29.0"
alembic = "^1.13.2"
httpx = "^0.27.2"
pytest = "^8.3.2"
pytest-cov = "^5.0.0"
uvloop = "^0.20.0"
httptools = "^0.6.1"
rich = "^13.8.0"
pyjwt = {version = "^2.9.0", extras = ["cryptography"]}
redis = "^5.0.8"
bcrypt = "^4.2.0"
polars = "^1.6.0"
python-multipart = "^0.0.9"
fastexcel = "^0.11.6"
fastapi-cache2 = {git = "https://github.com/yoco-tech/fastapi-cache.git",  rev = "main"}
inline-snapshot = "^0.12.1"
dirty-equals = "^0.8.0"
polyfactory = "^2.16.2"
granian = "^1.5.2"
transformers = "^4.44.2"
apscheduler = {version = "^4.0.0a5", extras = ["redis,sqlalchemy"]}

[tool.poetry.group.dev.dependencies]
devtools = { extras = ["pygments"], version = "^0.12.2" }
safety = "*"
pyupgrade = "*"
ipython = "^8.26.0"
ruff = "^0.6.1"
sqlacodegen = "^3.0.0rc5"
tryceratops = "^2.3.3"
locust = "^2.31.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120
indent-width = 4

lint.select = ["E", "F", "UP", "N", "C", "B"]
lint.ignore = ["E501"]

# Exclude a variety of commonly ignored directories.
exclude = ["alembic",]
# Assume Python 3.12
target-version = "py312"

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends",]

[tool.pytest.ini_options]
addopts = "-v --doctest-modules --doctest-glob=*.md --ignore=alembic"
asyncio_mode = "strict"
env_files = [".env"]

[tool.tryceratops]
exclude = ["alembic",]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"